SlovenskiKino/Controllers/ArhivController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlovenskiKino.Models;

namespace SlovenskiKino.Controllers
{
    public class ArhivController : Controller
    {
        private readonly KinoContext _context;

        public ArhivController(KinoContext context)
        {
            _context = context;
        }

        // GET: Arhiv
        public async Task<IActionResult> Index()
        {
            return View(await _context.ArhivFilmov.ToListAsync());
        }

        // GET: Arhiv/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arhivFilmov = await _context.ArhivFilmov
                .FirstOrDefaultAsync(m => m.IdFilma == id);
            if (arhivFilmov == null)
            {
                return NotFound();
            }

            return View(arhivFilmov);
        }

        // GET: Arhiv/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Arhiv/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdFilma,SlovenskiNaslov,AngleskiNaslov,Zanr,Dolzina,Datum")] ArhivFilmov arhivFilmov)
        {
            if (ModelState.IsValid)
            {
                _context.Add(arhivFilmov);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(arhivFilmov);
        }

        // GET: Arhiv/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arhivFilmov = await _context.ArhivFilmov.FindAsync(id);
            if (arhivFilmov == null)
            {
                return NotFound();
            }
            return View(arhivFilmov);
        }

        // POST: Arhiv/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdFilma,SlovenskiNaslov,AngleskiNaslov,Zanr,Dolzina,Datum")] ArhivFilmov arhivFilmov)
        {
            if (id != arhivFilmov.IdFilma)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(arhivFilmov);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArhivFilmovExists(arhivFilmov.IdFilma))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(arhivFilmov);
        }

        // GET: Arhiv/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var arhivFilmov = await _context.ArhivFilmov
                .FirstOrDefaultAsync(m => m.IdFilma == id);
            if (arhivFilmov == null)
            {
                return NotFound();
            }

            return View(arhivFilmov);
        }

        // POST: Arhiv/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var arhivFilmov = await _context.ArhivFilmov.FindAsync(id);
            _context.ArhivFilmov.Remove(arhivFilmov);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArhivFilmovExists(int id)
        {
            return _context.ArhivFilmov.Any(e => e.IdFilma == id);
        }
    }
}

SlovenskiKino/Controllers/DvoraneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlovenskiKino.Models;

namespace SlovenskiKino.Controllers
{
    public class DvoraneController : Controller
    {
        private readonly KinoContext _context;

        public DvoraneController(KinoContext context)
        {
            _context = context;
        }

        // GET: Dvorane
        public async Task<IActionResult> Index()
        {
            var kinoContext = _context.InfoOdvoranah.Include(i => i.IdKinematografNavigation);
            return View(await kinoContext.ToListAsync());
        }

        // GET: Dvorane/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var infoOdvoranah = await _context.InfoOdvoranah
                .Include(i => i.IdKinematografNavigation)
                .FirstOrDefaultAsync(m => m.IdInfo == id);
            if (infoOdvoranah == null)
            {
                return NotFound();
            }

            return View(infoOdvoranah);
        }

        // GET: Dvorane/Create
        public IActionResult Create()
        {
            ViewData["IdKinematograf"] = new SelectList(_context.Kinematografi, "IdKinematograf", "IdKinematograf");
            return View();
        }

        // POST: Dvorane/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdInfo,IdKinematograf,Dvorana,SteviloSedezov,SteviloVrst,InvalidskiSedezi,Podpora3D")] InfoOdvoranah infoOdvoranah)
        {
            if (ModelState.IsValid)
            {
                _context.Add(infoOdvoranah);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKinematograf"] = new SelectList(_context.Kinematografi, "IdKinematograf", "IdKinematograf", infoOdvoranah.IdKinematograf);
            return View(infoOdvoranah);
        }

        // GET: Dvorane/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var infoOdvoranah = await _context.InfoOdvoranah.FindAsync(id);
            if (infoOdvoranah == null)
            {
                return NotFound();
            }
            ViewData["IdKinematograf"] = new SelectList(_context.Kinematografi, "IdKinematograf", "IdKinematograf", infoOdvoranah.IdKinematograf);
            return View(infoOdvoranah);
        }

        // POST: Dvorane/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdInfo,IdKinematograf,Dvorana,SteviloSedezov,SteviloVrst,InvalidskiSedezi,Podpora3D")] InfoOdvoranah infoOdvoranah)
        {
            if (id != infoOdvoranah.IdInfo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(infoOdvoranah);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InfoOdvoranahExists(infoOdvoranah.IdInfo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdKinematograf"] = new SelectList(_context.Kinematografi, "IdKinematograf", "IdKinematograf", infoOdvoranah.IdKinematograf);
            return View(infoOdvoranah);
        }

        // GET: Dvorane/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var infoOdvoranah = await _context.InfoOdvoranah
                .Include(i => i.IdKinematografNavigation)
                .FirstOrDefaultAsync(m => m.IdInfo == id);
            if (infoOdvoranah == null)
            {
                return NotFound();
            }

            return View(infoOdvoranah);
        }

        // POST: Dvorane/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var infoOdvoranah = await _context.InfoOdvoranah.FindAsync(id);
            _context.InfoOdvoranah.Remove(infoOdvoranah);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InfoOdvoranahExists(int id)
        {
            return _context.InfoOdvoranah.Any(e => e.IdInfo == id);
        }
    }
}

SlovenskiKino/Controllers/KinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SlovenskiKino.Models;

namespace SlovenskiKino.Controllers
{
    public class KinoController : Controller
    {
        private readonly KinoContext _context;

        public KinoController(KinoContext context)
        {
            _context = context;
        }

        // GET: Kino
        public async Task<IActionResult> Index()
        {
            var kinoContext = _context.Kinematografi.Include(k => k.IdPodjetjaNavigation);
            return View(await kinoContext.ToListAsync());
        }

        // GET: Kino/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kinematografi = await _context.Kinematografi
                .Include(k => k.IdPodjetjaNavigation)
                .FirstOrDefaultAsync(m => m.IdKinematograf == id);
            if (kinematografi == null)
            {
                return NotFound();
            }

            return View(kinematografi);
        }

        // GET: Kino/Create
        public IActionResult Create()
        {
            ViewData["IdPodjetja"] = new SelectList(_context.Podjetja, "IdPodjetja", "IdPodjetja");
            return View();
        }

        // POST: Kino/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKinematograf,IdPodjetja,Kinematograf")] Kinematografi kinematografi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kinematografi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPodjetja"] = new SelectList(_context.Podjetja, "IdPodjetja", "IdPodjetja", kinematografi.IdPodjetja);
            return View(kinematografi);
        }

        // GET: Kino/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kinematografi = await _context.Kinematografi.FindAsync(id);
            if (kinematografi == null)
            {
                return NotFound();
            }
            ViewData["IdPodjetja"] = new SelectList(_context.Podjetja, "IdPodjetja", "IdPodjetja", kinematografi.IdPodjetja);
            return View(kinematografi);
        }

        // POST: Kino/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKinematograf,IdPodjetja,Kinematograf")] Kinematografi kinematografi)
        {
            if (id != kinematografi.IdKinematograf)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kinematografi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KinematografiExists(kinematografi.IdKinematograf))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdPodjetja"] = new SelectList(_context.Podjetja, "IdPodjetja", "IdPodjetja", kinematografi.IdPodjetja);
            return View(kinematografi);
        }

        // GET: Kino/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kinematografi = await _context.Kinematografi
                .Include(k => k.IdPodjetjaNavigation)
                .FirstOrDefaultAsync(m => m.IdKinematograf == id);
            if (kinematografi == null)
            {
                return NotFound();
            }

            return View(kinematografi);
        }

        // POST: Kino/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kinematografi = await _context.Kinematografi.FindAsync(id);
            _context.Kinematografi.Remove(kinematografi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KinematografiExists(int id)
        {
            return _context.Kinematografi.Any(e => e.IdKinematograf == id);
        }
    }
}

SlovenskiKino/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Slovenski Kino</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/navbar.min.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .mynav-bar {
            overflow: hidden;
            background-color: #333;
            font-family: Arial, Helvetica, sans-serif;
        }

        .mynav-navbar a {
            float: left;
            font-size: 16px;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .mynav-dropdown {
            float: left;
            overflow: hidden;
        }

            .mynav-dropdown .mynav-dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 10px 10px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }

            .mynav-navbar a:hover, .mynav-dropdown:hover .mynav-dropbtn {
                background-color: red;
            }

        .mynav-dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .mynav-dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .mynav-dropdown-content a:hover {
                    background-color: #ddd;
                }

        .mynav-dropdown:hover .mynav-dropdown-content {
            display: block;
            margin: 10;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="mynav-navbar">
                <div class="mynav-dropdown">
                    <button class="mynav-dropbtn">
                        <a asp-area="" asp-controller="Aktualno" asp-action="Index" class="navbar-brand">Slovenski Kino</a>
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="mynav-dropdown-content">
                        <a asp-area="" asp-controller="Aktualno" asp-action="Index">Aktualno</a>
                        <a asp-area="" asp-controller="Arhiv" asp-action="Index">Arhiv</a>
                        <a asp-area="" asp-controller="Dvorane" asp-action="Index">Dvorane</a>
                        <a asp-area="" asp-controller="Kino" asp-action="Index">Kino</a>
                        <a asp-area="" asp-controller="Napovednik" asp-action="Index">Napovednik</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SlovenskiKino</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>